### ISSUE TITLE
Elastickube UI page blank

### ISSUE THREAD

**Issue by madhu25** [ElasticBox/elastickube#17]
I have setup Elastickube with my kubernetes cluster on bare metal ubuntu machines. Elastickube server is running but my UI page for Elastickube is blank. What could be the reason?

**Comment by albertoarias** [comment]
@madhu25 I have seen this issue when elastickube is unable to find the kubernetes endpoint. By default we search for a service in the `kube-system` namespace called `kubernetes` and connect to the https port using the token stored on the service account secret. 

The easiest way to fix this issue is specifying the internal unsecured endpoint during the deployment using the following command:

curl -s https://elastickube.com | bash -s -- -u http://<IP address kube-apiserver>:<unscured port typically 8080>
 
@ShadySQL has been helping debug the install process on this thread, check it out: https://github.com/ElasticBox/elastickube/issues/11

**Comment by madhu25** [comment]
Thanks..it helped!
