### ISSUE TITLE
Doesn't show newly created namespaces.

### ISSUE THREAD

**Issue by madhu25** [ElasticBox/elastickube#89]
When I create a new namespace, it doesn't show newly created namespaces. It only shows already deployed namespaces. Why?

**Comment by paulino-corujo** [comment]
@madhu25 can you post this info?:
- Browser and version the issue is happening on
- Is it happening when you create a namespace using ElasticKube or when you manually create a new namespace in Kubernetes.
- Is there any error in the javascript log console?
- If you reload the ElasticKube application does it comes up?

**Comment by madhu25** [comment]
- Chrome 
- It is happening both ways when I create namespace using ElasticKube and manually
- No error
- No it doesn't

**Comment by arnaud-elasticbox** [comment]
@madhu25 thanks for reporting the issue. I was able to reproduce the issue and I have submitted a fix:
https://github.com/ElasticBox/elastickube/pull/95

**Comment by madhu25** [comment]
Thanks :)

**Comment by arnaud-elasticbox** [comment]
Pull request merged, closing it.
